name: Docker Push

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           submodules: recursive
      - name: Get current date
        id: date
        run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.date.outputs.date }}
          tag_exists_error: false
          message: ""
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t pyiron/nfdi_demonstrators:latest nfdi_demonstrators/
      - run: docker tag pyiron/nfdi_demonstrators:latest pyiron/nfdi_demonstrators:"$(date +%F)"
      - run: docker images
      - run: docker push pyiron/nfdi_demonstrators:latest
      - run: docker push pyiron/nfdi_demonstrators:"$(date +%F)"
