name: Docker Push

on: workflow_dispatch


jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1.7.2
        id: "tag_create"
        with:
          tag: ${{ steps.date.outputs.date }}
          tag_exists_error: false
          message: ""
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
           submodules: recursive
      - name: Get current date
        id: date
        run: echo "date=$(date +%F)" >> $GITHUB_OUTPUT
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t niklassiemer/pyiron4nfdmatwerk_examples:latest nfdi_demonstrators/
      - run: docker tag niklassiemer/pyiron4nfdmatwerk_examples:latest niklassiemer/pyiron4nfdmatwerk_examples:"$(date +%F)"
      - run: docker images
      - run: docker push niklassiemer/pyiron4nfdmatwerk_examples:latest
      - run: docker push niklassiemer/pyiron4nfdmatwerk_examples:"$(date +%F)"
